packages:
  - .
resolver: nightly-2024-10-31
compiler: ghc-9.10.1
compiler-check: match-exact
extra-deps:
  - base-4.20.0.1
  - bytestring-0.12.1.0
  - deepseq-1.5.1.0
  - mtl-2.3.1
  - time-1.14
  - transformers-0.6.1.2
